### ISSUE TITLE
Performance overhead with active record

### ISSUE THREAD

**Issue by kbaum** [socialpandas/sidekiq_monitor#12]
Cool project.  Will job execution time be significantly slower since this uses active record? 

Thx!

**Comment by tombenner** [comment]
Depending on what "significantly means", yes or no. A (fairly simple) write occurs every time a job is created or has its status updated (e.g. "queued" to "running"), and there are probably approximately as many reads as writes.

The very small numbers of milliseconds (usually < 10ms) that this adds to our job execution time hasn't been an issue at all for us at SocialPandas. As is usual with performance, you may want to test it yourself and see whether its performance suits your needs.
