### ISSUE TITLE
Ensure proper urls when parent rails app mounted at relative url

### ISSUE THREAD

**Issue by thoughtchad** [socialpandas/sidekiq_monitor#17]
When rails app is deployed to web context other than / (root), sidekiq_monitor's url helpers do not include the relative url mount point. This breaks the general top nav links and the jquery api calls.

This fixes it: chad-lancour@97d8c8dc354928784bf2864fc913343caa91fa0e

**Comment by tombenner** [comment]
Fixed in 0.1.2 (with 1e3de7ef74006b69d8b586a4fd690ac0cc5b7d8c). Thanks!
