### ISSUE TITLE
Mysql dependency 

### ISSUE THREAD

**Issue by sahin** [socialpandas/sidekiq_monitor#18]
Is there any strong reason for mysql dependency? 

Why are not we using redis instead of mysql? 

We are planing to fork the project a build a redis version if it is ok?

**Comment by tombenner** [comment]
The main reasons we used a relational database were 1) to easily support filtering and searches against multiple columns of jobs in the UI (when you click "Queued" and type a value into the search box, for example) and 2) to make our own internal reporting queries easier.

A fork that uses Redis would be fantastic; I'm sure other users want this, too. You'd need to work out how to support the filtering/searching, of course. Definitely let me know if you do this, and we could talk about how to let users choose whether they use Redis or ActiveRecord.
