### ISSUE TITLE
Ability to sort by Interrupted status

### ISSUE THREAD

**Issue by kitwalker12** [socialpandas/sidekiq_monitor#19]
The Jobs I schedule via perform_at or jobs that are scheduled via the sidetiq gem are shown with a status of interrupted, instead of queued. Can we add a column which shows 'Interrupted' state jobs along with 'Queued', 'Running', 'Complete' & 'Failed'

**Comment by tombenner** [comment]
Adding targeted support for a single gem probably doesn't make sense, but a method for adding other statuses to the UI actually already exists; I just hadn't had time to document it yet. You'll want to add the following (in an initializer, if you're in Rails):

``` ruby
# config/initializers/sidekiq_monitor.rb
Sidekiq::Monitor::Job.add_status('interrupted')
```

I've documented [this](https://github.com/socialpandas/sidekiq_monitor#custom-statuses), along with [Custom Job Views](https://github.com/socialpandas/sidekiq_monitor#custom-job-views) (another previously-undocumented feature) to the README.

Thanks for requesting this! I should've had this documentation done earlier.
