### ISSUE TITLE
Error when I add a new item to sidekiq

### ISSUE THREAD

**Issue by 45sound** [socialpandas/sidekiq_monitor#23]
Fresh install:

```
sidekiq-status (0.5.0)
  sidekiq (>= 2.7, < 3.1)

sidekiq (3.0.2)
  celluloid (>= 0.15.2)
  connection_pool (>= 2.0.0)
  json
  redis (>= 3.0.6)
  redis-namespace (>= 1.3.1)
```

BackupAudioS3Queue.perform_async(23)

ArgumentError: wrong number of arguments (4 for 3)
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq_monitor-0.1.3/lib/sidekiq/monitor/client/middleware.rb:9:in `call'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:124:in`block in invoke'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-unique-jobs-3.0.0/lib/sidekiq-unique-jobs/middleware/client/unique_jobs.rb:15:in `call'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:124:in`block in invoke'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:127:in `call'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:127:in`invoke'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-3.0.2/lib/sidekiq/client.rb:201:in `process_single'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-3.0.2/lib/sidekiq/client.rb:65:in`push'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-3.0.2/lib/sidekiq/worker.rb:85:in `client_push'
    from /home/v/.rvm/gems/ruby-2.0.0-p247/gems/sidekiq-3.0.2/lib/sidekiq/worker.rb:40:in`perform_async'

**Comment by tombenner** [comment]
This was due to a lack of support for Sidekiq 3, which was resolved by #20. This fix is available in version 0.1.4.
