### ISSUE TITLE
File to import not found or unreadable: dataTables/jquery.dataTables.bootstrap

### ISSUE THREAD

**Issue by marino-mrc** [socialpandas/sidekiq_monitor#27]
in /home/ntt/.rvm/gems/ruby-2.1.1/gems/sidekiq_monitor-0.1.4/app/assets/stylesheets/sidekiq/monitor/application.css.sass:3 there is the @import of datatables. 
If I change from
@import dataTables/jquery.dataTables.bootstrap
to
@import dataTables/bootstrap/2/jquery.dataTables.bootstrap

It works well. Is an issue related to my own ruby/rails installation or is a common issue?

**Comment by knightq** [comment]
Same problem: it does not work with Bootstrap 2.x

**Comment by jcope2013** [comment]
+1, willing to accept a PR for this? or provide an alternate solution?

**Comment by dnd** [comment]
Can jcope2013's fix be brought in, so that an unofficial fork doesn't have to be used? It seems pretty simple, and the app doesn't work at all right now as it stands.

**Comment by tombenner** [comment]
Thanks, all! I've merged #33, and this is now available in 0.1.7.
