### ISSUE TITLE
undefined method `configure_client' for Sidekiq:Module (NoMethodError)

### ISSUE THREAD

**Issue by pokonski** [socialpandas/sidekiq_monitor#3]
I receive 

```
sidekiq-monitor-3dc03f52654a/lib/sidekiq/monitor.rb:14:in `<top (required)>': undefined method `configure_client' for Sidekiq:Module (NoMethodError)
```

when trying to run `rails g sidekiq:monitor:install`

The version of Sidekiq I have installed is `2.8`

**Comment by squarism** [comment]
Wondering why this was closed.  I'm having the same issue.  Did you find a solution?

**Comment by pokonski** [comment]
I wish I remembered the details :( I think I mismatched versions.
