### ISSUE TITLE
Sass::SyntaxError - File to import not found or unreadable: dataTables/jquery.dataTables.bootstrap

### ISSUE THREAD

**Issue by alexnesbitt** [socialpandas/sidekiq_monitor#4]
Any idea what I am doing wrong? I get the following error when I try to got the sidekiq_monitor ui:

Sass::SyntaxError in Sidekiq/monitor/jobs#index

Showing /home/xxx/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq_monitor-0.0.3/app/views/sidekiq/monitor/layouts/application.slim where line #6 raised:

File to import not found or unreadable: dataTables/jquery.dataTables.bootstrap.
Load paths:
  Sass::Rails::Importer(/home/xxx/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq_monitor-0.0.3/app/assets/stylesheets/sidekiq/monitor/application.css.sass)
  /var/www/dp3/app/assets/stylesheets
  /home/xxx/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/frameworks/blueprint/stylesheets
  /home/xxx/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/frameworks/compass/stylesheets
  /home/xxx/.rvm/gems/ruby-1.9.3-p194/gems/bootstrap-sass-2.3.2.0/vendor/assets/stylesheets
  Compass::SpriteImporter
  /var/www/vendor/assets/stylesheets
  (in /home/xxx/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq_monitor-0.0.3/app/assets/stylesheets/sidekiq/monitor/application.css.sass)

Extracted source (around line #6):

3:   meta charset="utf-8"
4:   meta name="viewport" content="width=device-width, initial-scale=1.0"
5:   title= content_for?(:title) ? yield(:title) : app_name
6:   = stylesheet_link_tag "sidekiq/monitor/application"
7:   = csrf_meta_tags
8: 
9:   body

**Comment by tombenner** [comment]
I've added @320c3c03, which should fix this, I believe. Could you try using master and seeing if the error is resolved?

``` ruby
gem 'sidekiq_monitor', :git => 'git://github.com/socialpandas/sidekiq_monitor'
```

**Comment by aemadrid** [comment]
The issue is still there. The jquery datatables gem [1] tells you to select bootstrap 2 or 3 by including the right file:

*= require dataTables/bootstrap/2/jquery.dataTables.bootstrap
or
*= require dataTables/bootstrap/3/jquery.dataTables.bootstrap

[1] https://github.com/rweng/jquery-datatables-rails
